import classnames from 'classnames';
import {Poppins, Baloo_Chettan_2} from 'next/font/google'
import "./globals.css";
import ClientOnly from '@/ui/ClientOnly';
import ToasterProvider from '@/providers/ToasterProvider';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const font = Poppins({subsets: ['latin'], weight: ['100', '200', '300', '400', '500', '500', '600', '700', '800', '900']})
const font2 = Baloo_Chettan_2({subsets: ['latin']})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={classnames("bg-[#f6f6f6] font-secondary", font.className, font2.className)}>
        <ClientOnly>
          <ToasterProvider />
        </ClientOnly>
        {children}
      </body>
    </html>
  );
}
